/*
This class defines an object to store the information of a single transaction in a BankAccount
Each object records the amount of the transaction (negative for withdrawals), the updated balance
after the transaction, and the date/time the transaction took place
 */

import java.time.LocalDateTime;

public class TransactionRecord {
    //instance variables
    private final double amountTransacted; //how much was withdrawn or deposited? (negative for withdrawal)
    private final double updatedBalance; //the balance of the account after the transaction
    private final LocalDateTime dateTimeOfTransaction;

    //standard constructor generated by IntelliJ
    public TransactionRecord(double amountTransacted, double updatedBalance, LocalDateTime dateTimeOfTransaction) {
        this.amountTransacted = amountTransacted;
        this.updatedBalance = updatedBalance;
        this.dateTimeOfTransaction = dateTimeOfTransaction;
    }

    //standard getter methods generated by IntelliJ
    public double getAmountTransacted() {
        return amountTransacted;
    }

    public double getUpdatedBalance() {
        return updatedBalance;
    }

    public LocalDateTime getDateTimeOfTransaction() {
        return dateTimeOfTransaction;
    }

    //toString() method to be able to print out this TransactionRecord nicely
    public String toString() {
        return "Transaction at " + dateTimeOfTransaction + " of $" +
                String.format("%.2f", amountTransacted) + " new balance: " +
                String.format("%.2f", updatedBalance);
    }
}
